#pytest.ini

[pytest]
minversion = 7.0
pythonpath = src
testpaths = tests
addopts = 
    -v
    --strict-markers
    --tb=short
    --disable-warnings
markers =
    pe: Pruebas de particion de equivalencia
    vl: Pruebas de valores limite
    unit: Pruebas unitarias
    integration: Pruebas de integracion
    system: Pruebas de sistema
